# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cf45cd13f1c0527d8d84239fc8fa84b4329e57e381b0c1c69549ca8718322fdf441666520cc57f529653ee98e7d26ded1007dc214d1e5a2dbd7595e099d8255

test:
  secret_key_base: 3194b166cba001ff6a10b3abe371d78db4bd029b2f03e5b2cb9656c7db4c2c414eb3f36ad60fddf66ad577581b9b53f8cb4ed905171ba01f267781039e685c66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
